apiVersion: v1
kind: ConfigMap
metadata:
  name: spam-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/model_bundle.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: spam
  MODEL_ALIAS: champion
